#!/bin/bash
# wrapper to fastq_pre_barcodes
# Generates a BAM file with unaligned reads and all barcodes preprocessed
VERSION="0.16.0""0.15.1"

command -v fastq_pre_barcodes   >/dev/null 2>&1 || { echo "ERROR: fastq_utils does not seem to be installed - fastq_pre_barcodes not found.  Aborting." >&2; exit 1; }
command -v samtools   >/dev/null 2>&1 || { echo "ERROR: fastq_utils does not seem to be installed - samtools not found.  Aborting." >&2; exit 1; }

##########################################################
#
function pinfo {
    echo "[INFO] $*" > /dev/stderr
}

function perror {
    echo "[ERROR] $*" > /dev/stderr
}

function usage() {
    echo "fastq2bam $VERSION="0.16.0""0.15.1""
    echo "Usage: fastq2bam -s schema -b out_bam -1 fastqfile1 [ -2 fastqfile2 -3 fastqfile3 -4 fastqfile4]"
    echo "barcode schema: 10xV1 10xV1i 10xV1a 10xV2 drop-seq none"
}

function gen_bam() {
    cmd=$*
    set -eo pipefail
    cmd="$cmd --sam --outfile1 - | samtools view -b - > $bam_file.tmp && mv $bam_file.tmp $bam_file"
    echo $cmd
    bash -c "set -eo pipefail; $cmd"
}

##########################################################
##
schema=
bam_file=
fastq_file1=
fastq_file2=
fastq_file3=
fastq_file4=

while getopts "b:s:a:1:2:3:4:h"  Option
do
    case $Option in
        b ) bam_file=$OPTARG;;
	s ) schema=$OPTARG;;
	a ) schema=$OPTARG;;
	1 ) fastq_file1=$OPTARG;;
	2 ) fastq_file2=$OPTARG;;
	3 ) fastq_file3=$OPTARG;;
	4 ) fastq_file4=$OPTARG;;
        h ) usage; exit 0;;
    esac
done

if [ "$*-" == "-" ] || [ "$schema-" == "-" ]; then
    usage
    exit 1
fi

if [ "$bam_file-" == "-" ] ; then
    usage
    exit 1
fi

#schema=$1
#out_bam=$2
#shift 2

pinfo schema=$schema
pinfo bam_file=$bam_file
pinfo fastq1=$fastq_file1
pinfo fastq2=$fastq_file2
pinfo fastq3=$fastq_file3


if [ "$schema-"  == "10xV2-" ]; then
    # index1=R1 file index2=I1 reads=R2
    if [ "$fastq_file2-"  == "-" ]; then
	echo "Missing files for $schema:"
	echo "-1 cell#16|umi#10 -2 cdna -3 [-3 sample#8]"
	echo "e.g., -1 *R1*.fastq.gz -2 *R2*.fastq.gz [-3 *I1*.fastq.gz]"
	usage
	exit 1
    fi
    cmd="fastq_pre_barcodes --read1 $fastq_file2 --index1 $fastq_file1 --umi_read index1 --umi_offset 16 --umi_size 10 --cell_read index1 --cell_offset 0 --cell_size 16"
    if [ "$fastq_file3-" != "-" ]; then
	cmd="$cmd --index2 $fastq_file3 --sample_read index2 --sample_offset 0 --sample_size 8" 
    fi
    gen_bam $cmd
    exit 0
fi

if [ "$schema-"  == "10xV1-" ]; then
    # index1=read2/I7, index2=I5
    if [ "$fastq_file2-"  == "-" ]; then
	echo "Missing files for $schema:"
	echo "-1 cdna  -2 cell#14|umi#10 [-3 sample#8]"
	echo "e.g., -1 *R1*.fastq.gz -2 *R2*.fastq.gz  [-3 *I5*.fastq.gz]"
	usage
	exit 1
    fi
    cmd="fastq_pre_barcodes --read1 $fastq_file1 --index1 $fastq_file2 --index1 $fastq_file2 --umi_read index1 --umi_offset 14 --umi_size 10 --cell_read index1 --cell_offset 0 --cell_size 14"
    if [ "$fastq_file3-" != "-" ]; then
	cmd="$cmd  --index2 $fastq_file2 --sample_read index2 --sample_offset 0 --sample_size 8" 
    fi
    gen_bam $cmd
    exit 0
fi


if [ "$schema-"  == "10xV1a-" ]; then
    # fastq_file1 = read_RA*_1 = cdna
    # fastq_file2 = index3=read_RA*_2 = UMI
    # fastq_file3 = index1=*I1* = cell barcode
    # fastq_file4 = index2=*I2* = sample barcodes
    if [ "$fastq_file2-"  == "-" ] || [ "$fastq_file3-" == "-" ]; then
	echo "Missing files for $schema:"
	echo "-1 cdna  -2 umi#10 -3 cell#14 [-4 sample#8]"
	echo "e.g., -1 *RA_1.fastq.gz -2 *RA_2.fastq.gz -3 *I1*.fastq.gz [-4 *I2*.fastq.gz]"
	usage
	exit 1
    fi

    cmd="fastq_pre_barcodes --read1 $fastq_file1 --index3 $fastq_file2 --index1 $fastq_file3 --umi_read index3 --umi_offset 0 --umi_size 10 --cell_read index1 --cell_offset 0 --cell_size 14"
    if [ "$fastq_file4-"  != "-" ]; then
	cmd="$cmd  --index3 $fastq_file4 --sample_read index2 --sample_offset 0 --sample_size 8"
    fi
    gen_bam $cmd
    exit 0
fi

if [ "$schema-"  == "10xV1i-" ]; then
    # fastq_file1 = read_RA*_1 = cdna & index3=read_RA*_2 = UMI
    # fastq_file2 = index1=*I1* = cell barcode
    # fastq_file3 = index2=*I2* = sample barcodes
    if [ "$fastq_file2-"  == "-" ]; then
	echo "Missing files for $schema:"
	echo "-1 cdna/umi#10 -2 cell#14  [-3 sample#8]"
	echo "e.g., -1 *RA*.fastq.gz -2 *I1*.fastq.gz [-3 *I2*.fastq.gz]"
	usage
	exit 1
    fi

    cmd="fastq_pre_barcodes --read1 $fastq_file1 --index3 $fastq_file1 --index1 $fastq_file2 --umi_read index3 --umi_offset 0 --umi_size 10 --cell_read index1 --cell_offset 0 --cell_size 14 --interleaved read1,index3"
    if [ "$fastq_file3-"  != "-" ]; then
	cmd="$cmd  --index2 $fastq_file3 --sample_read index2 --sample_offset 0 --sample_size 8"
    fi
    gen_bam $cmd
    exit 0
fi


if [ "$schema-"  == "dropseq-" ]; then
    pinfo "schema $schema under development"
    if [ "$fastq_file2-"  == "-" ]; then
	echo "Missing files for $schema:"
	echo "-1 umi#8|cell#12 -2 cdna"
	echo "e.g., -1 *_1.fastq.gz -2 *_2.fastq.gz"
	usage
	exit 1
    fi
    cmd="fastq_pre_barcodes --read1 $fastq_file2 --index1 $fastq_file1 --umi_read index1 --umi_offset 12 --umi_size 8 --cell_read index1 --cell_offset 0 --cell_size 12"
    gen_bam $cmd

    exit 0
fi

if [ "$schema-"  == "none-" ]; then
    cmd="fastq_pre_barcodes --read1 $fastq_file1"
    if [ "$fastq_file2-" != "-" ]; then
	cmd="$cmd  --read2 $fastq_file2" 
    fi
    gen_bam $cmd
    exit 0
fi

pinfo "Unknown  schema $schema"
exit 1


